- name: "loop practice"
  hosts: "local"
  connection: "local"
  become: "yes"
  tasks: 
  - name: "printing the names"
    ansible.builtin.debug:
      msg: "Hello {{item.Name}} your id is {{item.id}}"
    loop: [{Name: "Vinay", id: 24}, {Name: "Siva", id: 46}]
      
